# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v .
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0

    - name: Test
      run: go test -v .

    - name: Zip the aws-lambda binary
      run: zip prun-tools.zip prun-tools

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name $AWS_LAMBDA_NAME \
          --zip-file fileb://./prun-tools.zip \
          --region $AWS_REGION
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_LAMBDA_NAME: ${{ secrets.AWS_LAMBDA_NAME }}
        AWS_REGION: ${{ vars.AWS_REGION }}

    - name: Wait 1 minute before invoking lambda
      run: sleep 60
      
    - name: Invoke Lambda
      run: |
        aws lambda invoke \
        --function-name $AWS_LAMBDA_NAME
        out.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_LAMBDA_NAME: ${{ secrets.AWS_LAMBDA_NAME }}
        AWS_REGION: ${{ vars.AWS_REGION }}
